apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi-bff
  namespace: apps
  labels:
    app: fastapi-bff
    tier: gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fastapi-bff
  template:
    metadata:
      labels:
        app: fastapi-bff
    spec:
      imagePullSecrets:
        - name: dockerhub-registry-credentials
      containers:
        - name: fastapi-bff
          image: creedx66/fastapi-bff:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8000
              name: http
          env:
            # Telemetria OpenTelemetry -> Grafana Alloy
            - name: OTEL_SERVICE_NAME
              value: "fastapi-bff"
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: "http://alloy.observability.svc.cluster.local:4317"
            - name: OTEL_EXPORTER_OTLP_PROTOCOL
              value: "grpc"
            # Conexões de Microsserviços
            - name: AUTH_SERVICE_GRPC_ADDR
              value: "auth-service.apps.svc.cluster.local:50051"
            - name: USER_SERVICE_GRPC_ADDR
              value: "user-service.apps.svc.cluster.local:50052"
            - name: EVENT_SERVICE_GRPC_ADDR
              value: "event-service.apps.svc.cluster.local:50053"
            - name: REDIS_HOST
              value: "redis.data.svc.cluster.local"
            - name: REDIS_PORT
              value: "6379"
          resources:
            requests:
              cpu: 50m
              memory: 128Mi
            limits:
              cpu: 250m
              memory: 512Mi
          livenessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 10
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: fastapi-bff
  namespace: apps
  labels:
    app: fastapi-bff
spec:
  selector:
    app: fastapi-bff
  ports:
    - port: 8000
      targetPort: 8000
      name: http

