apiVersion: v1
kind: Secret
metadata:
  name: databases-credentials
  namespace: data
type: Opaque
stringData:
  POSTGRES_USER: "postgres"
  POSTGRES_PASSWORD: "<CHANGE_ME_POSTGRES_PASSWORD>"
  POSTGRES_DB: "ticket_booking"
  RABBITMQ_DEFAULT_USER: "rabbit_admin"
  RABBITMQ_DEFAULT_PASS: "<CHANGE_ME_RABBITMQ_PASSWORD>"
  MONGO_INITDB_ROOT_USERNAME: "mongo_admin"
  MONGO_INITDB_ROOT_PASSWORD: "<CHANGE_ME_MONGO_PASSWORD>"
  REDIS_PASSWORD: "<CHANGE_ME_REDIS_PASSWORD>"
