apiVersion: v1
kind: Secret
metadata:
  name: databases-credentials
  namespace: data
type: Opaque
stringData:
  POSTGRES_USER: "postgres"
  POSTGRES_PASSWORD: "postgresSuperSecurePassword123!"
  POSTGRES_DB: "ticket_booking"
  RABBITMQ_DEFAULT_USER: "rabbit_admin"
  RABBITMQ_DEFAULT_PASS: "rabbitSecurePass123!"
  MONGO_INITDB_ROOT_USERNAME: "mongo_admin"
  MONGO_INITDB_ROOT_PASSWORD: "mongoSecurePass123!"
  REDIS_PASSWORD: "redisSecurePass123!"

