apiVersion: v1
kind: Secret
metadata:
  name: dockerhub-registry-credentials
  namespace: apps
type: kubernetes.io/dockerconfigjson
# Gere o json com:
# kubectl create secret docker-registry dockerhub-registry-credentials --docker-server=https://index.docker.io/v1/ --docker-username=SEU_USER --docker-password=SEU_TOKEN --dry-run=client -o yaml
stringData:
  .dockerconfigjson: |
    {
      "auths": {
        "https://index.docker.io/v1/": {
          "username": "SEU_DOCKERHUB_USERNAME",
          "password": "SEU_DOCKERHUB_TOKEN",
          "auth": "BASE64_USER_TOKEN"
        }
      }
    }

