apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ingress/api-ingress.yaml
  - ingress/grafana-ingress.yaml
  - ingress/portainer-ingress.yaml
  - ingress/traefik-middlewares.yaml
  - observability/alloy-configmap.yaml
  - observability/loki.yaml
  - observability/mimir.yaml
  - observability/tempo.yaml
  - apps/fastapi-bff/deployment.yaml
