apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ingress/grafana-ingress.yaml
  - ingress/portainer-ingress.yaml
  - ingress/traefik-middlewares.yaml
  - observability/alloy-configmap.yaml
  - observability/loki.yaml
  - observability/mimir.yaml
  - observability/tempo.yaml
  - observability/grafana-admin.enc.yaml
  - observability/network-policy.yaml
